version: "3.9"

services:
  api:
    build:
      context: ./ReleaseHub
    container_name: releasehub-api
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: releasehub-frontend
    ports:
      - "8080:80"
    depends_on:
      - api