"""
Reconstruction of the paper's six-classifier comparison, run against the
real 1,000-note dataset. This is NOT a replication of Table 1. The
original pipeline's feature extraction/hyperparameters/train-test split
were never recovered (see repo README). Every choice below is disclosed
so it's clear what's original vs. reconstructed:

  - Labels: generated by the published label_component_type.py /
    label_security_type.py keyword matchers (../label/), run against
    the real dataset text. Release Type is generated by release_type.py in
    this folder (major/minor/patch, inferred from each note's own version
    number, see that file's docstring).
  - Component Type reduction rule (needed because the keyword matcher is
    multi-label but the paper describes this as multi-class/single-label):
    take the alphabetically-first matched category; "NONE" if no match.
  - Security Risk framed as BINARY (the paper itself describes Security
    Risk as binary classification).
  - Feature extraction: CountVectorizer (bag-of-words), matches the one
    confirmed detail from the real classifier code that was found
    (see repo README).
  - Train/test split: 80/20, not stratified (Component Type has some
    categories with only 1 note, which stratified splitting can't handle),
    random_state=42.
  - Six classifiers, mostly-default hyperparameters.

Usage:
    pip install pandas pyarrow scikit-learn matplotlib
    python train_and_evaluate.py path/to/data.parquet

    Get data.parquet from the Hugging Face dataset (see main repo README),
    e.g.:
    curl -L "https://huggingface.co/datasets/sberhe/2023-1000-software-release-notes/resolve/refs%2Fconvert%2Fparquet/default/train/0000.parquet" -o data.parquet
"""

import sys
from pathlib import Path

import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, cohen_kappa_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC

THIS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(THIS_DIR / ".." / "label"))
sys.path.insert(0, str(THIS_DIR))

from label_component_type import classify_text as label_component
from label_security_type import classify_text as label_security
from release_type import release_type

DATA_PATH = Path(sys.argv[1]) if len(sys.argv) > 1 else THIS_DIR / "data.parquet"
if not DATA_PATH.exists():
    raise SystemExit(
        f"Dataset not found at {DATA_PATH}. Download it first (see this file's "
        f"docstring) or pass a path: python train_and_evaluate.py path/to/data.parquet"
    )

TEST_SIZE = 0.2  # 80/20

df = pd.read_parquet(DATA_PATH)
texts = df["text"].tolist()

# --- Build labels ---
component_labels = []
security_labels = []
release_type_labels = []

for text in texts:
    comp = label_component(text)
    component_labels.append(sorted(comp)[0] if comp else "NONE")

    sec, _ = label_security(text)
    is_security = any(l != "UNKNOWN" for l in sec)
    security_labels.append("SECURITY" if is_security else "NOT_SECURITY")

    release_type_labels.append(release_type(text))

label_sets = {
    "Component Type": component_labels,
    "Security Risk": security_labels,
    "Release Type": release_type_labels,
}

for name, labels in label_sets.items():
    dist = pd.Series(labels).value_counts()
    print(f"{name} label distribution (top 5):")
    print(dist.head(5).to_string())
    print()

# --- Classifiers matching Table 1's six ---
CLASSIFIERS = {
    "Multinomial Naive Bayes": lambda: MultinomialNB(),
    "SVM (Linear Kernel)": lambda: SVC(kernel="linear"),
    "Logistic Regression": lambda: LogisticRegression(max_iter=1000),
    "Random Forest": lambda: RandomForestClassifier(random_state=42),
    "Gradient Boosting": lambda: GradientBoostingClassifier(random_state=42),
    "K-Nearest Neighbors": lambda: KNeighborsClassifier(),
}

results = {}  # {category: {classifier: accuracy}}
kappas = {}   # {category: {classifier: cohen_kappa}}

for category_name, labels in label_sets.items():
    X_train, X_test, y_train, y_test = train_test_split(
        texts, labels, test_size=TEST_SIZE, random_state=42
    )

    # Majority-class baseline: what a classifier gets "for free" by always
    # predicting the most common label in the training set.
    majority_label = pd.Series(y_train).value_counts().idxmax()
    baseline_acc = accuracy_score(y_test, [majority_label] * len(y_test))
    print(f"{category_name}: majority-class baseline = {majority_label!r} -> {baseline_acc*100:.1f}%")

    results[category_name] = {"__baseline__": baseline_acc}
    kappas[category_name] = {}
    for clf_name, clf_factory in CLASSIFIERS.items():
        pipeline = make_pipeline(CountVectorizer(), clf_factory())
        pipeline.fit(X_train, y_train)
        y_pred = pipeline.predict(X_test)
        acc = accuracy_score(y_test, y_pred)
        kappa = cohen_kappa_score(y_test, y_pred)
        results[category_name][clf_name] = acc
        kappas[category_name][clf_name] = kappa

n_test = int(len(texts) * TEST_SIZE)
n_train = len(texts) - n_test
print(f"=== Held-out test accuracy ({int(TEST_SIZE*100)}% split, n={n_train} train / {n_test} test) ===")

# Paper's Table 1 (Berhe et al. 2024), for comparison only. Not the same
# pipeline/labels/split; see repo README.
PAPER_TABLE_1 = {
    "Multinomial Naive Bayes": {"Component Type": "72%", "Security Risk": "92%", "Release Type": "Incorrect"},
    "SVM (Linear Kernel)": {"Component Type": "77%", "Security Risk": "94%", "Release Type": "Incorrect"},
    "Logistic Regression": {"Component Type": "88%", "Security Risk": "99%", "Release Type": "Incorrect"},
    "Random Forest": {"Component Type": "77%", "Security Risk": "94%", "Release Type": "Incorrect"},
    "Gradient Boosting": {"Component Type": "70%", "Security Risk": "94%", "Release Type": "Incorrect"},
    "K-Nearest Neighbors": {"Component Type": "58%", "Security Risk": "81%", "Release Type": "Incorrect"},
}

summary_rows = []
baseline_row = {"Classifier": "(majority-class baseline)"}
for category_name in label_sets:
    baseline_row[f"{category_name} (this run)"] = f"{results[category_name]['__baseline__']*100:.1f}%"
    baseline_row[f"{category_name} (paper)"] = ""
summary_rows.append(baseline_row)

for clf_name in CLASSIFIERS:
    row = {"Classifier": clf_name}
    for category_name in label_sets:
        acc = results[category_name][clf_name]
        base = results[category_name]["__baseline__"]
        row[f"{category_name} (this run)"] = f"{acc*100:.1f}% (+{(acc-base)*100:.1f} pts)"
        row[f"{category_name} (paper)"] = PAPER_TABLE_1[clf_name][category_name]
    summary_rows.append(row)

summary_df = pd.DataFrame(summary_rows).set_index("Classifier")
print(summary_df.to_string())
summary_df.to_csv(THIS_DIR / "classifier_results.csv")

print("\n=== Cohen's Kappa (chance-adjusted agreement) ===")
kappa_rows = []
for clf_name in CLASSIFIERS:
    row = {"Classifier": clf_name}
    for category_name in label_sets:
        row[category_name] = f"{kappas[category_name][clf_name]:.3f}"
    kappa_rows.append(row)
kappa_df = pd.DataFrame(kappa_rows).set_index("Classifier")
print(kappa_df.to_string())
kappa_df.to_csv(THIS_DIR / "kappa_results.csv")
